# Generated by Django 3.0.5 on 2020-08-29 09:28

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

  initial = True

  dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
  operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('feedback', models.JSONField()),         ],
        ),
    ]
